[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

### Manage custom badges

# generate_card_ui()
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "local info_queue = {}"
match_indent = true
position = "after"
payload = '''
-- Add custom badges
if first_pass and badges then

    if _c.unique then
        -- Add the Unique badge
        badges[#badges + 1] = 'unique'
        info_queue[#info_queue+1] = {key = 'unique', set = 'Other'}
    end

    if _c.set == 'Curse' then
        -- Add the Curse badge
        badges[#badges + 1] = 'curse'
    end

    -- suit buffs
    if card_type == 'Enhanced' or card_type == 'Default' then
        if specific_vars.suit == 'Diamonds' and G.GAME.used_cu_augments and G.GAME.used_cu_augments.c_star_cu then
            badges[#badges + 1] = 'star_bu'
        elseif specific_vars.suit == 'Clubs' and G.GAME.used_cu_augments and G.GAME.used_cu_augments.c_moon_cu then
            badges[#badges + 1] = 'moon_bu'
        elseif specific_vars.suit == 'Hearts' and G.GAME.used_cu_augments and G.GAME.used_cu_augments.c_sun_cu then
            badges[#badges + 1] = 'sun_bu'
        elseif specific_vars.suit == 'Spades' and G.GAME.used_cu_augments and G.GAME.used_cu_augments.c_world_cu then
            badges[#badges + 1] = 'world_bu'
        end
        if SMODS.Mods and (SMODS.Mods['Bunco'] or {}).can_load then
            if specific_vars.suit == 'bunc_Fleurons' and G.GAME.used_cu_augments and G.GAME.used_cu_augments.c_bunc_sky_cu then
                badges[#badges + 1] = 'sky_bu'
            elseif specific_vars.suit == 'bunc_Halberds' and G.GAME.used_cu_augments and G.GAME.used_cu_augments.c_bunc_abyss_cu then
                badges[#badges + 1] = 'abyss_bu'
            end
        end
    end
end
'''
